### ISSUE TITLE
Importing configs from Krohnkite

### ISSUE THREAD

**Issue by glmsmoura** [gikari/bismuth#26]
Hello there! I was just searching for Krohnkite related stuff on github and found this project. It seems very promising for me, and I hope it goes well.

So, is there an easy way to import Krohnkite configs directly? I have some neat shortcuts and reconfiguring them seems a pain in the ass. 

Thanks for this project, really helpful!

**Comment by gikari** [comment]
Thank you for your contribution!

I will research this topic in the near time more deeply, provide instructions in the readme and provide bash script, that imports the shortcuts.

**Comment by gikari** [comment]
I'm just interested. What are your shortcuts actually? I personally find the Krohnkite ones suboptimal. Maybe we can change the defaults.

**Comment by glmsmoura** [comment]
Here is my Kwin shortcuts: https://termbin.com/m0t3

Basically:
I use meta as alt
Desktop changing -> meta + 1..0, to change between 1 to 10
Window to other desktop -> meta+shift+1..0 (it changes depending on your keyboard. Mine is brazil-abnt2, and ¨ is a composed character, so I had to use no dead keys layout for this to work. Kinda buggy sometimes, actually, but I learned how to dare with it.)
alt+h and alt+l to resize the tiling focused
meta+m to set master

**Comment by gikari** [comment]
I've made a PR with the import script. I think you would be interested in checking if it is working for you. Please, post your suggestions too if any on that PR.
