### ISSUE TITLE
Monocle "minimize others" prevents change of focus without minimizing first

### ISSUE THREAD

**Issue by bladedvox** [gikari/bismuth#55]
After the wayland patch that removes the timers, this feature is completely broken. The only way I can change focus is to minimize the current window first and then change focus to the desired window.

Perhaps to fix this we will need Actions that minimize/unminimize windows? I was thinking that might be nice anyways because the binding I usually use to activate a KWin task switcher that steps through minimized windows is OK (although this issue renders it ineffectual) but not quite the behavior I would like.

I will experiment in my branch to see if I can come up with a solution for this.

**Comment by gikari** [comment]
Do you mean the "Minimize unfocused windows" checkbox feature?

I actually do not like the way this feature was implemented and the fact, that it has the WIP status. In particular, I do not like, that it prevents from window switching using next/previous shortcuts. Is there any reason why this feature should exist in the first place? Why do one care about other windows minimization, if you're in the monocle layout anyway?

**Comment by bladedvox** [comment]
I use it -- since my terminals are transparent (85% opacity), it helps that when I use Monocle mode, the active window has nothing but the desktop wallpaper showing under it. I'm pretty sure this is the intended use-case.

**Comment by gikari** [comment]
Oh, this actually makes sense. Maybe it's worth making this feature work and enabled by default. Or maybe the toggle is not needed at all (although maybe someone wants to view the content of the previous window through transparency).

**Comment by bladedvox** [comment]
Yeah, if I have some energy left after work today I will try to get this working again.
