### ISSUE TITLE
[FEATURE]:  Missing "Cycle Layout" and "Float All" functions?"

### ISSUE THREAD

**Issue by ZacharyTalis** [gikari/bismuth#67]
### Summary

Problem: Krohnkite originally featured shortcuts for `Cycle Layout` and `Float All` functions. Are these replicated in Bismuth, or superseded by other functions? (I might be daft.)

### A clear and concise description of what you want to happen

Solution: Implement `Cycle Layout` and `Float All` functions and shortcuts. Make any language tweaks necessary to fit the new shortcut naming scheme.

### Additional info

Thank you for this wonderful fork <3

**Comment by gikari** [comment]
Yes, there are actions for that. Cycle Layout - is the Meta + \ shortcut (`Swith to the Next Layout`). And the Float All action is performed via `Toggle Floating Layout` (It is bound to `Meta+Shift+F` by default)

**Comment by ZacharyTalis** [comment]
Oh perfect! I just checked and can confirm that this is working.
