### ISSUE TITLE
[Bug]: "Toggle Quarter Layout" shortcut doesn't work

### ISSUE THREAD

**Issue by ZacharyTalis** [gikari/bismuth#68]
### Summary

The `Toggle Quarter Layout` shortcut does nothing, no matter what the shortcut is bound to.

Using `Switch to the Next Layout` to access Quarter Layout still works. Other layout shortcuts (including `Toggle Three Column Layout`) work.

### Steps to Reproduce

1. Go to `Settings > Shortcuts`
2. Add any shortcut binding to `System Services > Kwin > Bismuth: Toggle Quarter Layout`
3. Press the assigned binding.

### Expected behavior

Pressing the assigned shortcut should enable the Quarter Layout, with a dialog appearing at the center of the display.

### Screenshots

![image](https://user-images.githubusercontent.com/23324896/135167408-374dbaa7-cc3c-4f07-a5d2-5cb096ccac4a.png)

### Bismuth version

Latest from `master` branch

### KDE Plasma version

5.22.5

### The platform KWin is running on

X11

### Additional context

I took a look through the code but couldn't find a source for this unexpected behavior.

Debugging steps I've taken:
- Cleared my system of Krohnkite remnants
- Rebooted multiple times
- Uninstalled/reinstalled Bismuth multiple times
- Attempted to set a default shortcut binding in `src/controller/action.ts`, line 527. (No default shortcut appeared in the settings menu.)

Let me know if there's any other debugging steps I should take. Once we debug, I'll adjust this post's title to be more descriptive of the issue at hand.

And best of luck, I've got zero clue why the bug occurs o7

**Comment by gikari** [comment]
Thank you for contributing your time to debug the issue. Please, test if the #69 is working for you.

**Comment by ZacharyTalis** [comment]
> Thank you for contributing your time to debug the issue. Please, test if the #69 is working for you.

Yep, that's working! Thank youuuuu

![The Quarter tiling layout in action, with Firefox open to the fixed branch.](https://user-images.githubusercontent.com/23324896/135182699-b7195d82-0230-4b07-8be5-095c784a995e.png)
